### PR TITLE
fix: Route name missing for routes with children + Locale prefixes missing for child routes with custom paths

### LINKED ISSUE #356: Routes with children have no name thus localePath(route with children) always returns the root path
### Version

[5.12.7](https://github.com/nuxt-i18n/releases/tag/5.12.7)

### Reproduction link

[https://codesandbox.io/s/codesandbox-nuxt-8go7n](https://codesandbox.io/s/codesandbox-nuxt-8go7n)

### Steps to reproduce

On the home page, press the About button.

### What is expected ?

If the romanian language is selected, the button should redirect us to '/despre'.
If the english language is selected, the button should redirect us to 
'/en/about'

### What is actually happening?

The button, no matter what language is selected, redirects us to '/'

### Additional comments?

The problem comes from this line: https://github.com/nuxt-community/nuxt-i18n/blob/master/src/helpers/routes.js#L74

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c258">#c258</a>)</em></sub></div>

### PR DESCRIPTION
**Pull request by rchl**
PR includes two separate (but in the same family) bugs, in two separate commits.
Refer to individual commits messages for more info.

Resolves #356, #359

### CODE REVIEW

File: src/helpers/routes.js [hunk 1]
```diff
@@ -77,7 +77,6 @@ exports.makeRoutes = (baseRoutes, {
 
       // Generate localized children routes if any
       if (route.children) {
-        delete localizedRoute.name
```
Comment (rchl) [inline src/helpers/routes.js]: Actually I found out what issue removing route name was solving. In the case of directory structure like:
```
pages:
 - posts/index.vue
 - posts.vue
```
Nuxt will generate routes:
```
{
    path: '/posts',
    component: _f3e2cabc,
    children: [{
      path: '',
      component: _50b11fa5,
      name: 'posts'
    }]
  }
```

So the parent route doesn't have a name in this case, and if it had, VueRouter would trigger warning that child route is not accessible using `:to({ name: 'posts' })`.

So I need to look more into it. I guess the name should only be removed when there will be no child routes that would "shadow" parent's name.

Comment (rchl) [reply src/helpers/routes.js]: Addendum: This is an issue *when combined with* the fact that we are always setting name for extra routes added for locales. Then we can end up with multiple identical names that shadow each other.

Comment (rchl) [reply src/helpers/routes.js]: I believe I have it figured out now.
